package vista;


import modelo.Conexion;
import vista.*;
import java.sql.Connection;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Mayrita
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.btnAgregarC.setSelected(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnMenu = new rsbuttom.RSButtonMetro();
        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnAgregarC = new rsbuttom.RSButtonMetro();
        btnModificarC = new rsbuttom.RSButtonMetro();
        btnConsultarC = new rsbuttom.RSButtonMetro();
        btnFacturas = new rsbuttom.RSButtonMetro();
        btnPedidos = new rsbuttom.RSButtonMetro();
        btnWeb = new rsbuttom.RSButtonMetro();
        btnAcercaDe = new rsbuttom.RSButtonMetro();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnModificarE = new rsbuttom.RSButtonMetro();
        btnConsultarE = new rsbuttom.RSButtonMetro();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarF = new rsbuttom.RSButtonMetro();
        btnModificarC1 = new rsbuttom.RSButtonMetro();
        btnConsultarC1 = new rsbuttom.RSButtonMetro();
        btnStock = new rsbuttom.RSButtonMetro();
        btnAgregarE = new rsbuttom.RSButtonMetro();
        jLabel3 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));

        btnMenu.setBackground(new java.awt.Color(51, 102, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu.setColorHover(new java.awt.Color(51, 102, 255));
        btnMenu.setColorNormal(new java.awt.Color(51, 102, 255));
        btnMenu.setColorPressed(new java.awt.Color(51, 102, 255));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMenu.setBackground(new java.awt.Color(214, 217, 223));

        jPanel4.setBackground(new java.awt.Color(214, 217, 223));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        btnAgregarC.setBackground(new java.awt.Color(214, 217, 223));
        btnAgregarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnAgregarC.setText("Agregar");
        btnAgregarC.setColorHover(new java.awt.Color(204, 204, 204));
        btnAgregarC.setColorNormal(new java.awt.Color(214, 217, 223));
        btnAgregarC.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAgregarC.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAgregarC.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAgregarC.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAgregarC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregarC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregarC.setIconTextGap(25);
        btnAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCActionPerformed(evt);
            }
        });

        btnModificarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/collection.png"))); // NOI18N
        btnModificarC.setText("Modificar");
        btnModificarC.setColorHover(new java.awt.Color(204, 204, 204));
        btnModificarC.setColorNormal(new java.awt.Color(214, 217, 223));
        btnModificarC.setColorPressed(new java.awt.Color(204, 204, 204));
        btnModificarC.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnModificarC.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnModificarC.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnModificarC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificarC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarC.setIconTextGap(25);
        btnModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCActionPerformed(evt);
            }
        });

        btnConsultarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/feeedback.png"))); // NOI18N
        btnConsultarC.setText("Consultar");
        btnConsultarC.setAlignmentX(0.5F);
        btnConsultarC.setColorHover(new java.awt.Color(204, 204, 204));
        btnConsultarC.setColorNormal(new java.awt.Color(214, 217, 223));
        btnConsultarC.setColorPressed(new java.awt.Color(204, 204, 204));
        btnConsultarC.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnConsultarC.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnConsultarC.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnConsultarC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultarC.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultarC.setIconTextGap(25);
        btnConsultarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCActionPerformed(evt);
            }
        });

        btnFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnFacturas.setText("Facturas");
        btnFacturas.setColorHover(new java.awt.Color(204, 204, 204));
        btnFacturas.setColorNormal(new java.awt.Color(214, 217, 223));
        btnFacturas.setColorPressed(new java.awt.Color(204, 204, 204));
        btnFacturas.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnFacturas.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnFacturas.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnFacturas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFacturas.setIconTextGap(25);
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(204, 204, 204));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chat.png"))); // NOI18N
        btnPedidos.setText("Pedidos");
        btnPedidos.setColorHover(new java.awt.Color(204, 204, 204));
        btnPedidos.setColorNormal(new java.awt.Color(204, 204, 204));
        btnPedidos.setColorPressed(new java.awt.Color(204, 204, 204));
        btnPedidos.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnPedidos.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnPedidos.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnPedidos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPedidos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPedidos.setIconTextGap(25);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnWeb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/web.png"))); // NOI18N
        btnWeb.setText("WEB");
        btnWeb.setColorHover(new java.awt.Color(204, 204, 204));
        btnWeb.setColorNormal(new java.awt.Color(214, 217, 223));
        btnWeb.setColorPressed(new java.awt.Color(204, 204, 204));
        btnWeb.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnWeb.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnWeb.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnWeb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnWeb.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnWeb.setIconTextGap(25);
        btnWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWebActionPerformed(evt);
            }
        });

        btnAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ios.png"))); // NOI18N
        btnAcercaDe.setText("Acerca De");
        btnAcercaDe.setColorHover(new java.awt.Color(204, 204, 204));
        btnAcercaDe.setColorNormal(new java.awt.Color(214, 217, 223));
        btnAcercaDe.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAcercaDe.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAcercaDe.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAcercaDe.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAcercaDe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAcercaDe.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAcercaDe.setIconTextGap(25);
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(128, 128, 131));
        jLabel2.setText("productos");

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(128, 128, 131));
        jLabel1.setText("Clientes");

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(128, 128, 131));
        jLabel4.setText("ayuda");

        btnModificarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/android.png"))); // NOI18N
        btnModificarE.setText("Modificar");
        btnModificarE.setColorHover(new java.awt.Color(204, 204, 204));
        btnModificarE.setColorNormal(new java.awt.Color(214, 217, 223));
        btnModificarE.setColorPressed(new java.awt.Color(204, 204, 204));
        btnModificarE.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnModificarE.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnModificarE.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnModificarE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificarE.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarE.setIconTextGap(25);
        btnModificarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEActionPerformed(evt);
            }
        });

        btnConsultarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/android.png"))); // NOI18N
        btnConsultarE.setText("Consultar");
        btnConsultarE.setColorHover(new java.awt.Color(204, 204, 204));
        btnConsultarE.setColorNormal(new java.awt.Color(214, 217, 223));
        btnConsultarE.setColorPressed(new java.awt.Color(204, 204, 204));
        btnConsultarE.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnConsultarE.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnConsultarE.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnConsultarE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultarE.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultarE.setIconTextGap(25);
        btnConsultarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(128, 128, 131));
        jLabel5.setText("Vendedores");

        btnAgregarF.setBackground(new java.awt.Color(214, 217, 223));
        btnAgregarF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnAgregarF.setText("Agregar");
        btnAgregarF.setColorHover(new java.awt.Color(204, 204, 204));
        btnAgregarF.setColorNormal(new java.awt.Color(214, 217, 223));
        btnAgregarF.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAgregarF.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAgregarF.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAgregarF.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAgregarF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregarF.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregarF.setIconTextGap(25);
        btnAgregarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarFActionPerformed(evt);
            }
        });

        btnModificarC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/collection.png"))); // NOI18N
        btnModificarC1.setText("Modificar");
        btnModificarC1.setColorHover(new java.awt.Color(204, 204, 204));
        btnModificarC1.setColorNormal(new java.awt.Color(214, 217, 223));
        btnModificarC1.setColorPressed(new java.awt.Color(204, 204, 204));
        btnModificarC1.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnModificarC1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnModificarC1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnModificarC1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnModificarC1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarC1.setIconTextGap(25);
        btnModificarC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarC1ActionPerformed(evt);
            }
        });

        btnConsultarC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/feeedback.png"))); // NOI18N
        btnConsultarC1.setText("Consultar");
        btnConsultarC1.setAlignmentX(0.5F);
        btnConsultarC1.setColorHover(new java.awt.Color(204, 204, 204));
        btnConsultarC1.setColorNormal(new java.awt.Color(214, 217, 223));
        btnConsultarC1.setColorPressed(new java.awt.Color(204, 204, 204));
        btnConsultarC1.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnConsultarC1.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnConsultarC1.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnConsultarC1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultarC1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultarC1.setIconTextGap(25);
        btnConsultarC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarC1ActionPerformed(evt);
            }
        });

        btnStock.setBackground(new java.awt.Color(214, 217, 223));
        btnStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ios.png"))); // NOI18N
        btnStock.setText("Inventario");
        btnStock.setColorHover(new java.awt.Color(204, 204, 204));
        btnStock.setColorNormal(new java.awt.Color(214, 217, 223));
        btnStock.setColorPressed(new java.awt.Color(204, 204, 204));
        btnStock.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnStock.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnStock.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnStock.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnStock.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnStock.setIconTextGap(25);
        btnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockActionPerformed(evt);
            }
        });

        btnAgregarE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/android.png"))); // NOI18N
        btnAgregarE.setText("Agregar");
        btnAgregarE.setColorHover(new java.awt.Color(204, 204, 204));
        btnAgregarE.setColorNormal(new java.awt.Color(214, 217, 223));
        btnAgregarE.setColorPressed(new java.awt.Color(204, 204, 204));
        btnAgregarE.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnAgregarE.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnAgregarE.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnAgregarE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgregarE.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAgregarE.setIconTextGap(25);
        btnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(128, 128, 131));
        jLabel3.setText("Acciones");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAcercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarC1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificarE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlMenuLayout.createSequentialGroup()
                                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsultarC, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarE, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsultarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModificarC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 850, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = this.pnlMenu.getX();
        if (posicion > -1){
            Animacion.Animacion.mover_izquierda(0, -188, 2, 2, pnlMenu);
        }else{Animacion.Animacion.mover_derecha(-188, 0, 2, 2, pnlMenu);
            
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCActionPerformed
        
    }//GEN-LAST:event_btnAgregarCActionPerformed

    private void btnModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCActionPerformed
       
    }//GEN-LAST:event_btnModificarCActionPerformed

    private void btnConsultarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCActionPerformed
        
    }//GEN-LAST:event_btnConsultarCActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed
       
    }//GEN-LAST:event_btnFacturasActionPerformed

    private void btnConsultarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEActionPerformed
        
    }//GEN-LAST:event_btnConsultarEActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
        
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWebActionPerformed
        
    }//GEN-LAST:event_btnWebActionPerformed

    private void btnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEActionPerformed
        
    }//GEN-LAST:event_btnAgregarEActionPerformed

    private void btnModificarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEActionPerformed
        
    }//GEN-LAST:event_btnModificarEActionPerformed

    private void btnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockActionPerformed
        
    }//GEN-LAST:event_btnStockActionPerformed

    private void btnAgregarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarFActionPerformed

    private void btnModificarC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarC1ActionPerformed

    private void btnConsultarC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rsbuttom.RSButtonMetro btnAcercaDe;
    public rsbuttom.RSButtonMetro btnAgregarC;
    public rsbuttom.RSButtonMetro btnAgregarE;
    public rsbuttom.RSButtonMetro btnAgregarF;
    public rsbuttom.RSButtonMetro btnConsultarC;
    public rsbuttom.RSButtonMetro btnConsultarC1;
    public rsbuttom.RSButtonMetro btnConsultarE;
    public rsbuttom.RSButtonMetro btnFacturas;
    public rsbuttom.RSButtonMetro btnMenu;
    public rsbuttom.RSButtonMetro btnModificarC;
    public rsbuttom.RSButtonMetro btnModificarC1;
    public rsbuttom.RSButtonMetro btnModificarE;
    public rsbuttom.RSButtonMetro btnPedidos;
    public rsbuttom.RSButtonMetro btnStock;
    public rsbuttom.RSButtonMetro btnWeb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel pnlMenu;
    // End of variables declaration//GEN-END:variables
}
